config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  resources :events, only: [:index, :show]
  namespace :api, defaults: { format: :json } do
    resources :people, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :person,
    primary_key: :uniq_id,
    foreign_key: :person_id,
    class_name: :Person

  belongs_to :event,
    primary_key: :uniq_id,
    foreign_key: :event_id,
    class_name: :Event

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendances,
    primary_key: :uniq_id,
    foreign_key: :event_id,
    class_name: :Attendance

  has_many :people,
    through: :attendances,
    source: :person

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :attendances,
    primary_key: :uniq_id,
    foreign_key: :person_id,
    class_name: :Attendance

  has_many :events,
    through: :attendances,
    source: :event

end

app/controllers/api/people_controller.rb
class Api::PeopleController < ApplicationController

  def index
    render json: Person.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @people = @event.people
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/helpers/api/people_helper.rb
module Api::PeopleHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/events/index.html.erb
<div class="outer-div">
  <% @events.each do |event| %>
  <div class="inner-div">
    <p><%= event.name %></p>
    <p><%= event.location %></p>
    <p>$<%= event.price %></p>
    <p><%= event.date %></p>
    <p><%= link_to "Display event", event_url(event) %></p>
  </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="outer-div">
  <p><%= link_to "Go back to main page", events_url %></p>
  <% @event.people.each do |person| %>
    <div class="inner-div">
      <%= person.first_name %>
      <%= person.last_name %>
      <br>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>